# site settings
title: "Charles Helf for Congressional House of Representatives TX-CD1"
subtitle: "A grassroots candidate of, by, and for the ordinary Texan"
email:
description: "A true leader leads through example, and a true servant places others above himself"
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
formspreeid: mpwdnyvd
index_heading: "Before You Go: Share Your Thoughts"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/
  LinkedIn:
  Twitter: https://twitter.com/
  Facebook: https://www.facebook.com/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
