# site settings
title: "Charles Helf for Congress, House Rep TX-CD1"
subtitle: "A grassroots candidate of, by, and for the ordinary Texan"
email:
description: "A true leader leads through example, and a true servant places all others above himself"
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
formspreeid: mpwdnyvd
index_heading: "Before You Go: Share Your Thoughts"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/charles.helf.texas/
  LinkedIn:
  Twitter:
  Facebook: https://www.facebook.com/charles.helf.texas/
  Slack:
  TikTok: https://www.tiktok.com/@charles.helf.texas
  BlueSky: https://bsky.app/profile/charles-helf-texas.bsky.social
  YouTube: https://www.youtube.com/channel/UCp-mMhfP6ZI1z9dbOrjcAHA
  X: https://bsky.app/profile/charles-helf-texas.bsky.social

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
