# site settings
title: "Charles Helf TX"
subtitle: "A grassroots figure of, by, and for the ordinary Texan"
email: charles_helf_texas@gmail.com
description: "Let's get to know each other a little better. Believe it or not, I'm actually in this because I want to help you, rather than to help myself."
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 123 Somewhere Road
city: Townsville
state: TX
zip_code: 55555
country: United States of America
phone: (555) 555-5555
formspreeid: mpwdnyvd

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/
  GitLab:
  Google-Plus: https://plus.google.com/
  Instagram: https://www.instagram.com/
  LinkedIn: https://www.linkedin.com/
  Twitter: https://twitter.com/
  Facebook: https://www.facebook.com/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- elements.md
